name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    name: "Unit Tests"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ensure Xcode Version
        run: | 
          sudo xcode-select -s "/Applications/Xcode_12.3.app"

      - name: Build and Test
        run: swift test
