name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  test:
    name: Build and Test.
    runs-on: macos-12
    env:
      XCODE_SCHEME: "JWW Error Reporting"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.3'

      - name: Build and Test (macOS)
        run: |
          set -o pipefail && env NSUnbufferedIO=YES
          xcodebuild build-for-testing -usePackageSupportBuiltinSCM -scheme "$XCODE_SCHEME" -destination "platform=macOS" | xcpretty

      - name: Build and Test (iOS)
        run: |
          set -o pipefail && env NSUnbufferedIO=YES
          xcodebuild build-for-testing -usePackageSupportBuiltinSCM -scheme "$XCODE_SCHEME" -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty

      - name: Build and Test (tvOS)
        run: |
          set -o pipefail && env NSUnbufferedIO=YES
          xcodebuild build-for-testing -usePackageSupportBuiltinSCM -scheme "$XCODE_SCHEME" -destination "platform=tvOS Simulator,OS=latest,name=Apple TV" | xcpretty

      - name: Build and Test (watchOS)
        run: |
          set -o pipefail && env NSUnbufferedIO=YES
          xcodebuild build-for-testing -usePackageSupportBuiltinSCM -scheme "$XCODE_SCHEME" -destination "platform=watchOS Simulator,OS=latest,name=Apple Watch Series 7 - 45mm" | xcpretty

